steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
          ["build", "-t",
          "gcr.io/$PROJECT_ID/sehatin-api/sehatin-food-detection-api",
          "."]

  - name: "gcr.io/cloud-builders/docker"
    args:
          ["push",
          "gcr.io/$PROJECT_ID/sehatin-api/sehatin-food-detection-api"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "food-detection",
        "--image",
        "gcr.io/$PROJECT_ID/sehatin-api/sehatin-food-detection-api",
        "--region",
        "asia-southeast2",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
options:
  logging: CLOUD_LOGGING_ONLY