steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'asia-southeast2-docker.pkg.dev/sehatin-406505/sehatin-api/sehatin-food-detection-api',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'asia-southeast2-docker.pkg.dev/sehatin-406505/sehatin-api/sehatin-food-detection-api']

options:
  logging: CLOUD_LOGGING_ONLY